/**
* @file index.tsx
* @date 2021-03-06
* @author zhoubin
* @lastModify  2021-03-06
*/
/* <------------------------------------ **** DEPENDENCE IMPORT START **** ------------------------------------ */
/** This section will include all the necessary dependence for this tsx file */
import React, { useRef } from 'react';
import { Row } from 'antd';
import { useDispatch } from 'react-redux';
import * as actions from "../../../Store/Todolist/actions";
/* <------------------------------------ **** DEPENDENCE IMPORT END **** ------------------------------------ */
/* <------------------------------------ **** INTERFACE START **** ------------------------------------ */
/** This section will include all the interface for this tsx file */
/* <------------------------------------ **** INTERFACE END **** ------------------------------------ */
/* <------------------------------------ **** FUNCTION COMPONENT START **** ------------------------------------ */
const Header = (): JSX.Element => {
    /* <------------------------------------ **** STATE START **** ------------------------------------ */
    /************* This section will include this component HOOK function *************/
    const dispatch = useDispatch();

    const inputEl = useRef<HTMLInputElement>(null);
    /* <------------------------------------ **** STATE END **** ------------------------------------ */
    /* <------------------------------------ **** PARAMETER START **** ------------------------------------ */
    /************* This section will include this component parameter *************/
    /* <------------------------------------ **** PARAMETER END **** ------------------------------------ */
    /* <------------------------------------ **** FUNCTION START **** ------------------------------------ */
    /************* This section will include this component general function *************/
    const addTodo = () => {
        /**
         * Input the value
         * @constant
         * @type {string | undefined}
         *
         */
        const content: string | undefined = inputEl.current?.value.trim();
        if (content) {
            /**
             * A unique todoitem ID is generated by timestamp
             * @constant
             * @type {string}
             *
             */
            const id = (new Date()).getTime().toString();
            /**
             * Default add task not completed
             * @constant
             * @type {boolean}
             *
             */
            const done = false;
            dispatch(actions.addTodoAction({ id, content, done }));

        }

    }
    /* <------------------------------------ **** FUNCTION END **** ------------------------------------ */
    return (
        <Row>
            <input ref={inputEl} type="text" />
            <button onClick={addTodo}>添加</button>
            <button onClick={() => dispatch(actions.deleteTodoAction())}>删除</button>
        </Row>
    );
};
export default Header;
/* <------------------------------------ **** FUNCTION COMPONENT END **** ------------------------------------ */